# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment of Admin Pannel

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        fetch-depth: 0
        submodules: true
    - run: npm ci
    - run: NUXT_API_BASE_URL='https://api.dev.matchheroapp.ie/api' npx nuxi generate

    - name: install ssh keys
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/github_action.key
        ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        echo "$SSH_KEY" > ~/.ssh/github_action.key
        chmod 600 ~/.ssh/github_action.key

    - name: connect and pull
      run: |
        scp -i ~/.ssh/github_action.key -o StrictHostKeyChecking=no -r .output/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/admin.matchhero.ie/
        ssh -i ~/.ssh/github_action.key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
        cd /var/www/admin.matchhero.ie
        sudo chown -R ubuntu:www-data ."

